{
 "title": "SSH Connect",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "New connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, '1m', 0) AS \"time\", COUNT(docker_id) AS \"value\" FROM ssh_connect_log WHERE attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    }
   ]
  },
  {
   "title": "Shell connections",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT attempt_time, docker_id, attacker_ip, attacker_version, login, password, command_shell, shell FROM ssh_connect_log WHERE command_shell is NULL and length(shell) > 0 ORDER BY attempt_time DESC "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT command, count(id) FROM ssh_connect_log where command is not NULL group by 1 order by 2"
    }
   ]
  },
  {
   "title": "Connection log",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT attempt_time, docker_id, attacker_ip, attacker_version, login, password, command_shell, shell FROM ssh_connect_log ORDER BY attempt_time DESC "
    }
   ]
  }
 ]
}