{
 "title": "SSH Login attempts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dashboard_port",
    "label": "Port",
    "query": "select distinct dst_port from ssh_login_attempt order by 1 asc"
   },
   { "name": "group_time", "label": "Time Group Param", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Attempts per minute",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"password\" FROM ssh_login_attempt WHERE method = 'password' and dst_port = 22 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"pubkey\" FROM ssh_login_attempt WHERE method = 'publickey' and dst_port = 22 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"password-2222\" FROM ssh_login_attempt WHERE method = 'password' and dst_port = 2222 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"pubkey-2222\" FROM ssh_login_attempt WHERE method = 'publickey' and dst_port = 2222 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"password-222\" FROM ssh_login_attempt WHERE method = 'password' and dst_port = 222 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"pubkey-222\" FROM ssh_login_attempt WHERE method = 'publickey' and dst_port = 222 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, $group_time, 0) AS \"time\", COUNT(method) AS \"telnet\" FROM ssh_login_attempt WHERE method = 'password' and dst_port = 23 and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    }
   ]
  },
  {
   "title": "Last passwords",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT attempt_time, attacker_ip, attacker_version, login, password FROM ssh_login_attempt where method = 'password' and dst_port = $dashboard_port and attempt_time between $__timeFrom() and $__timeTo() order by id desc"
    }
   ]
  },
  {
   "title": "World map",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, attacker_ip, e.asn as \"ASN\", e.as_ as \"AS\", count(id) as \"attempts\" FROM ssh_login_attempt a join ip_entry e on e.ip = a.attacker_ip group by 1, 2, 3, 4, 5"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT login as name, COUNT(id) as value FROM ssh_login_attempt where method = 'none' GROUP BY 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "Passwords",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT password as Name, COUNT(id) as Value FROM ssh_login_attempt where password is not NULL and length(password) > 0 GROUP BY password order by 2 desc"
    }
   ]
  },
  {
   "title": "Longest password",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "rawSql": "select password as value, length(password), count(id) from ssh_login_attempt WHERE password is NOT NULL group by 1, 2 order by length(password) desc limit 50"
    }
   ]
  },
  {
   "title": "Total attempts count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM ssh_login_attempt WHERE (method = 'password' OR method = 'publickey') LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max attempts per session",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(attempt_number) FROM ssh_login_attempt LIMIT 50 "
    }
   ]
  },
  {
   "title": "Captured IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct attacker_ip) FROM ssh_login_attempt"
    }
   ]
  },
  {
   "title": "Unique logins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(distinct login) FROM ssh_login_attempt LIMIT 50 "
    }
   ]
  },
  {
   "title": "Unique passwords",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(distinct password) FROM ssh_login_attempt"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT attacker_version, COUNT(id) FROM ssh_login_attempt where method='connect' or attacker_version = 'telnet' GROUP BY attacker_version order by 2 desc"
    }
   ]
  },
  {
   "title": "login:password",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT login || ':' || password as name, count(id) as value FROM ssh_login_attempt where password is NOT NULL and length(password) > 0 group by 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "Password histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT length(password) FROM ssh_login_attempt where password is not NULL order by 1 asc "
    },
    { "table": "ssh_login_attempt" }
   ]
  },
  {
   "title": "Attempts per address",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT attacker_ip, COUNT(id) FROM ssh_login_attempt WHERE method = 'password' GROUP BY attacker_ip order by 2 desc"
    }
   ]
  },
  {
   "title": "Impact by AS",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'AS' || e.asn || ' ' || e.as_ as \"AS\", count(id) as \"attempts\" FROM ssh_login_attempt a join ip_entry e on e.ip = a.attacker_ip where method = 'connect' group by 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "Impact by country",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT country_name, count(id) as \"attempts\" FROM ssh_login_attempt a join ip_entry e on e.ip = a.attacker_ip where method = 'connect' group by 1"
    }
   ]
  },
  {
   "title": "Attempts histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT attempt_number FROM ssh_login_attempt where method = 'password' and attempt_number > 1"
    }
   ]
  },
  {
   "title": "Port impact",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ':' || dst_port, count(id) as \"attempts\" FROM ssh_login_attempt a where (method = 'connect' or attacker_version = 'telnet') and attempt_time between $__timeFrom() and $__timeTo() group by 1"
    }
   ]
  },
  {
   "title": "pubkey attempts",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT cert, count(id) FROM ssh_login_attempt where method = 'publickey' group by 1 order by 2 desc"
    }
   ]
  }
 ]
}