{
 "title": "TCP Scan",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Attempts per minute",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, '1m', 0) AS \"time\", COUNT(id) AS \"TCP\" FROM tcp_scan_log where proto = 'tcp' and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    },
    {
     "rawSql": "SELECT $__timeGroup(attempt_time, '1m', 0) AS \"time\", COUNT(id) AS \"UDP\" FROM tcp_scan_log where proto = 'udp' and attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    }
   ]
  },
  {
   "title": "Proto impact",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT proto AS \"Protocol\", COUNT(id) AS \"value\" FROM tcp_scan_log where attempt_time between $__timeFrom() and $__timeTo() group by 1 order by 1 asc"
    }
   ]
  },
  {
   "title": "TCP Port scan frequency",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT '*:' || dst_port::text as Name, COUNT(id) as Value FROM tcp_scan_log where proto = 'tcp' GROUP BY 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "UDP Port scan frequency",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT '*:' || dst_port::text as Name, COUNT(id) as Value FROM tcp_scan_log where proto = 'udp' GROUP BY 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "Scan entries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM tcp_scan_log LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT attacker_ip, count(id) as \"attempts\" FROM tcp_scan_log a group by 1 order by 2 desc"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, attacker_ip, e.asn as \"ASN\", e.as_ as \"AS\", count(id) as \"attempts\" FROM tcp_scan_log a join ip_entry e on e.ip = a.attacker_ip group by 1, 2, 3, 4, 5"
    }
   ]
  }
 ]
}